apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}
  labels:
    app: {{ .Values.database.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
        - name: {{ .Values.database.name }}
          image: "{{ .Values.database.image }}:{{ .Values.database.imageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "dlottery.fullname" . }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: {{ .Values.database.volume.name }}
              mountPath: {{ .Values.database.volume.mountPath }}
      volumes:
        - name: {{ .Values.database.volume.name }}
          hostPath:
            path: {{ .Values.database.volume.hostPath }}
