apiVersion: v1
kind: Service
metadata:
  name: {{ include "dlottery.fullname" . }}
  labels:
    {{- include "dlottery.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "dlottery.fullname" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
spec:
  selector: 
    app: {{ .Values.database.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: 3306
